### ISSUE TITLE
Error on accessing empty cart

### ISSUE THREAD

**Issue by TheTracerBullet** [doublethreedigital/docs-starter-kit#44]
After installing and updating through `composer update`, if you attempt to navigate to the empty cart it returns a TypeError stating:

> Argument 1 passed to DoubleThreeDigital\SimpleCommerce\Repositories\CartRepository::find() must be of the type string, null given, called in [directory]/rad-ecommerce-store/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 261

**Comment by damcclean** [comment]
What are you doing before you run into this error?

**Comment by TheTracerBullet** [comment]
Just navigating to the cart in a brand new starter-kit site with no changes implemented (other than updating to the latest version) throws the error.

**Comment by TheTracerBullet** [comment]
Apologies, this is the wrong repository for this issue. Will close and re-open in the correct repository.
